### ISSUE TITLE
rewind a resource that is already declared twice

### ISSUE THREAD

**Issue by mancdaz** [bryanwb/chef-rewind#6]
The opsode apache cookbook actually clones the apache ports.conf template resource in the default and mod_ssl recipes:

If I want to rewind that resource in my own wrapper cookbook, and try to use chef-rewind, it appears to only find a single instance of the resource (maybe the first one), and rewind it.  But I still end up with the template from presumably the second declaration of the resource

```
[2013-04-29T17:03:10+00:00] WARN: Previous template[/etc/apache2/ports.conf]: /var/chef/cache/cookbooks/apache2/recipes/default.rb:195:in `from_file'
[2013-04-29T17:03:10+00:00] WARN: Current  template[/etc/apache2/ports.conf]: /var/chef/cache/cookbooks/apache2/recipes/mod_ssl.rb:37:in `from_file'
[2013-04-29T17:03:10+00:00] INFO: Resource template[/etc/apache2/ports.conf] found, now rewinding it
```

I know cloning the resource in the first instance is _a bad thing_, but is there some way to make chef-rewind match and rewind all instances of the resource, effectively consolidating them into a single resource declaration?

**Comment by thommay** [comment]
I tested this, and found that (with current master) I just needed the second rewind block; the first was superfluous. Can you test with the 0.0.9 release and confirm this?
